### ISSUE TITLE
Struggling to Install Module

### ISSUE THREAD

**Issue by sterlingmd17** [alx9r/PsOmsa#11]
Hey there I feel bad asking this on such an old script of yours. For some reason I am having the toughest time getting this module installed. Are there specific module files im supposed to use for this or is this master branch the whole module. Really like this script by the way and is exactly what i need to automate some big mundane tasks of mine.

**Comment by sterlingmd17** [comment]
yee i feel stupid i got it lol

**Comment by sterlingmd17** [comment]
yeee i feel stupid i got it lol

**Comment by alx9r** [comment]
@sterlingmd17 No problem.  I'm a bit surprised this module turned out to be useful in 2019.  There's no need to feel bad for asking.  I do try to respond to these issues eventually.  The response might not be to your satisfaction, but there's no harm in asking politely as you did.
